import { useState } from 'react';
import './SecondaryViews.css';
import { useToast } from '../contexts/ToastContext';
import { DEMO_STATE } from '../data/mockData';

interface PlaceholderProps {
  title: string;
  description: string;
}

export function ViewPlaceholder({ title, description }: PlaceholderProps) {
  return (
    <div className="view-placeholder">
      <div className="placeholder-content">
        <h2>{title}</h2>
        <p>{description}</p>
        <div className="placeholder-alert">
          This is a secondary view. For the prototype, the Live Operations view contains the complete implementation.
        </div>
      </div>
    </div>
  );
}

export function DiagnosisView() {
  const { diagnosis } = DEMO_STATE;
  const alert = diagnosis.alerts[0];

  return (
    <div className="secondary-view-container">
      <div className="view-header">
        <h2>Explainable AI Diagnosis (Demo)</h2>
        <span className="badge demo-badge">SIMULATED OUTPUT</span>
      </div>
      
      <div className="diagnosis-grid">
        <div className="panel diagnosis-panel">
          <div className="diag-row">
            <span className="diag-label">Anomaly Hypothesis</span>
            <span className="diag-value highlight-warning">{alert.hypothesis}</span>
          </div>
          <div className="diag-row">
            <span className="diag-label">Model Confidence</span>
            <span className="diag-value">{alert.confidence}%</span>
          </div>
          <div className="diag-row">
            <span className="diag-label">Primary Evidence</span>
            <ul className="diag-list">
              {alert.evidence.map((ev, i) => <li key={i}>{ev}</li>)}
            </ul>
          </div>
          <div className="diag-row">
            <span className="diag-label">Affected Telemetry</span>
            <div className="diag-tags">
              {alert.affectedTelemetry.map(t => <span key={t} className="tag">{t}</span>)}
            </div>
          </div>
          <div className="diag-row">
            <span className="diag-label">Recommended Operator Action</span>
            <span className="diag-value">{alert.recommendedAction}</span>
          </div>
          
          <div className="disclaimer-alert mt-4">
            <strong>DISCLAIMER:</strong> This is a simulated advisory generated by the demonstrator model, not a confirmed mechanical diagnosis.
          </div>
        </div>
      </div>
    </div>
  );
}

export function TrendsView() {
  const { rul } = DEMO_STATE;

  return (
    <div className="secondary-view-container">
      <div className="view-header">
        <h2>Trends & Remaining Useful Life (RUL)</h2>
        <span className="badge demo-badge">DEMO MODEL</span>
      </div>

      <div className="rul-grid">
        <div className="panel rul-main">
          <h3>Estimated Remaining Useful Life</h3>
          <div className="rul-value">{rul.rulEstimate} <span>Hours</span></div>
          <div className="rul-sub">Confidence Interval: {rul.confidenceInterval}</div>
        </div>
        
        <div className="panel rul-stats">
          <div className="rul-stat-row">
            <span>Health Index Trajectory</span>
            <span className="trend-down">-2.4% / 100hrs</span>
          </div>
          <div className="rul-stat-row">
            <span>Twin Deviation</span>
            <span className="trend-up">+11%</span>
          </div>
          <div className="rul-stat-row">
            <span>Thermal Drift</span>
            <span className="trend-up">+3.5°C / 100hrs</span>
          </div>
          <div className="rul-stat-row">
            <span>Maintenance Horizon</span>
            <span>{rul.maintenanceHorizon}</span>
          </div>
        </div>
      </div>

      <div className="panel mt-4">
        <h3>XAI Explainability Notes</h3>
        <ul className="xai-list">
          {rul.explainabilityNotes.map((note, i) => (
            <li key={i}>{note}</li>
          ))}
        </ul>
        <div className="placeholder-box mt-4">Future connection: SHAP values / feature importance chart</div>
      </div>
    </div>
  );
}

export function ReplayView() {
  const { showToast } = useToast();
  const { events, mission } = DEMO_STATE;
  
  return (
    <div className="secondary-view-container">
      <div className="view-header">
        <h2>Mission Replay: {mission.missionId}</h2>
      </div>

      <div className="replay-layout">
        <div className="replay-main">
          <div className="placeholder-box large">
            <span className="badge">MAP PLACEHOLDER</span>
            <p>Mission coordinates and animated UAV marker will be connected here.</p>
          </div>
          <div className="replay-controls">
            <button className="btn btn-secondary" onClick={() => showToast('Replay placeholder: connect playback engine')}>Play</button>
            <input type="range" className="scrubber" min="0" max="100" defaultValue="45" />
            <span className="time-display">{mission.utcTimestamp}</span>
          </div>
        </div>
        
        <div className="replay-sidebar">
          <div className="panel">
            <h3>Mission Events</h3>
            <div className="event-timeline">
              {events.map(ev => (
                <div className="timeline-item" key={ev.id}>
                  <div className="time">{new Date(ev.time).toLocaleTimeString('en-GB', {timeZone: 'UTC'})}</div>
                  <div className={`event-desc severity-${ev.severity}`}>{ev.fault}</div>
                </div>
              ))}
            </div>
          </div>
          <div className="panel mt-4">
            <h3>Health Summary</h3>
            <div>Start: {DEMO_STATE.health.healthStart}%</div>
            <div>End: {DEMO_STATE.health.healthEnd}%</div>
          </div>
        </div>
      </div>
    </div>
  );
}

export function SimulationView() {
  const { showToast } = useToast();
  const [scenario, setScenario] = useState('baseline');

  const scenarios: Record<string, any> = {
    baseline: { name: 'Baseline Cruise', thermal: '+0°C', fuel: 'Normal', healthLoss: '0.1%', rulImpact: '-1 hr' },
    highAlt: { name: 'High-Altitude Endurance', thermal: '-12°C', fuel: '+5%', healthLoss: '0.15%', rulImpact: '-2 hr' },
    hotWeather: { name: 'Hot-Weather Endurance', thermal: '+18°C', fuel: '+2%', healthLoss: '0.4%', rulImpact: '-6 hr' },
    rapidThrottle: { name: 'Rapid Throttle Transition', thermal: '+5°C', fuel: '+15%', healthLoss: '0.8%', rulImpact: '-12 hr' },
  };

  const current = scenarios[scenario];

  return (
    <div className="secondary-view-container">
      <div className="view-header">
        <h2>Engine Simulation Model</h2>
        <span className="badge demo-badge">LOCAL MODEL DEMO</span>
      </div>

      <div className="sim-layout">
        <div className="panel sim-selector">
          <h3>Scenarios</h3>
          <div className="scenario-list">
            {Object.entries(scenarios).map(([key, s]) => (
              <button 
                key={key}
                className={`sim-btn ${scenario === key ? 'active' : ''}`}
                onClick={() => setScenario(key)}
              >
                {s.name}
              </button>
            ))}
          </div>
          <button className="btn btn-primary mt-4" onClick={() => showToast('Simulating ' + current.name)}>Run Simulation</button>
        </div>

        <div className="panel sim-results">
          <h3>Predicted Outputs</h3>
          <div className="result-grid">
            <div className="result-item">
              <span className="res-label">Thermal Margin Impact</span>
              <span className="res-val">{current.thermal}</span>
            </div>
            <div className="result-item">
              <span className="res-label">Fuel Efficiency</span>
              <span className="res-val">{current.fuel}</span>
            </div>
            <div className="result-item">
              <span className="res-label">Predicted Health Loss</span>
              <span className="res-val">{current.healthLoss}</span>
            </div>
            <div className="result-item">
              <span className="res-label">RUL Impact</span>
              <span className="res-val">{current.rulImpact}</span>
            </div>
          </div>
          <div className="placeholder-box mt-4">
            Future connection: Detailed physics-based simulation graphs.
          </div>
        </div>
      </div>
    </div>
  );
}

export function HistoryView() {
  const { events } = DEMO_STATE;

  return (
    <div className="secondary-view-container">
      <div className="view-header">
        <h2>Event & Fault History</h2>
      </div>

      <div className="panel table-panel">
        <div className="table-responsive">
          <table className="history-table">
            <thead>
              <tr>
                <th>Time (UTC)</th>
                <th>Mission ID</th>
                <th>Event / Fault</th>
                <th>Severity</th>
                <th>Confidence</th>
                <th>Action Taken</th>
              </tr>
            </thead>
            <tbody>
              {events.map(ev => (
                <tr key={ev.id}>
                  <td>{new Date(ev.time).toLocaleString('en-GB', {timeZone: 'UTC'})}</td>
                  <td>{ev.missionId}</td>
                  <td>{ev.fault}</td>
                  <td><span className={`badge severity-${ev.severity}`}>{ev.severity.toUpperCase()}</span></td>
                  <td>{ev.confidence}%</td>
                  <td>{ev.actionTaken}</td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  );
}
